openapi: 3.0.1
info:
  title: '@jupiterone/graph-zoom'
  description: JupiterOne integration for ingesting data from Zoom
  x-cortex-git:
    github:
      repository: JupiterOne/graph-zoom
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-zoom'
